plugins {
    id 'fabric-loom' version '1.5-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

java {
//    toolchain {
//        languageVersion = JavaLanguageVersion.of(17)
//    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 17
}

loom {
//    include "META-INF/jars/*"
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://maven.fabricmc.net/' }
    maven { url 'https://masa.dy.fi/maven'}
    maven { url 'https://libraries.minecraft.net/'}
    maven { url 'https://www.cursemaven.com' }
    maven { url 'https://maven.quiltmc.org/repository/release/'}
    maven { url 'https://repo.spongepowered.org/maven/' }
    maven { url 'https://jitpack.io' }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // Using masa.dy.fi maven for Litematica and Malilib
    modImplementation "curse.maven:litematica-308892:5170070"
    modImplementation "fi.dy.masa.malilib:malilib-fabric-1.20.4:0.18.1"
    implementation "com.google.code.findbugs:jsr305:3.0.2"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}
tasks.register('buildAndGather') {
    subprojects {
        dependsOn project.tasks.named('build').get()
    }
    doFirst {
        println 'Gathering builds'
        def buildLibs = {
            p -> p.buildDir.toPath().resolve('libs')
        }
        delete fileTree(buildLibs(rootProject)) {
            include '*'
        }
        subprojects {
            copy {
                from(buildLibs(project)) {
                    include '*.jar'
                    exclude '*-dev.jar', '*-sources.jar', '*-shadow.jar'
                }
                into buildLibs(rootProject)
                duplicatesStrategy = DuplicatesStrategy.INCLUDE
            }
        }
    }
}
